Sum function completed
Cornpop456/ginzburg-victor-otus pull request #1
Opened 2018-07-26 10:08 UTC by Cornpop456

2018-07-26 18:36 UTC, korzio requested changes

2018-07-26 18:36 UTC, korzio commented on javascript/sum.js
> +		if (!value) return inner.sum || 'Нет переданных значений';
Означает ли это, что функция была вызвана без аргументов?

2018-07-26 18:45 UTC, Cornpop456 commented on javascript/sum.js
> +		if (!value) return inner.sum || 'Нет переданных значений';
Ага, проверка на наличие аргумента -  !undefined будет давать true

2018-07-27 11:03 UTC, korzio commented on javascript/sum.js
> +		if (!value) return inner.sum || 'Нет переданных значений';
А если передано `0`?

2018-07-27 11:58 UTC, Cornpop456 commented on javascript/sum.js
> +		if (!value) return inner.sum || 'Нет переданных значений';
Тоже даст true, исправил ошибку

2018-07-27 12:45 UTC, korzio commented on javascript/sum.js
> +		if (!value) return inner.sum || 'Нет переданных значений';
Вообще правильнее делать проверку на `arguments.length`, мало ли что подразумевается под `undefined`

2018-07-27 12:45 UTC, korzio approved these changes

2018-07-27 15:16 UTC, Cornpop456 commented on javascript/sum.js
> +		if (!value) return inner.sum || 'Нет переданных значений';
Ок и отрефакторил заодно немного

2018-07-27 15:28 UTC, merged