promiseReduce completed
Cornpop456/ginzburg-victor-otus pull request #2
Opened 2018-08-01 16:20 UTC by Cornpop456

2018-08-04 08:51 UTC, thoughtspile requested changes
Виктор, добрый день! 

Решение работает, но код получился немного запутанным (как обычно бывает с рекурсией). Удобно было бы использовать встроенный метод массива `reduce` — попробуете?

Вопросы по граничным условиям:

- Может ли reducer быть асинхронным?
- Что произойдет, если во время создания промиса произойдет ошибка? А в `reduce`? А в самом промисе?

2018-08-04 09:54 UTC, Cornpop456 commented
Добрый день, переделал, пришлось использовать async await синтаксис, иначе не получалось вернуть значение из reduce в then, по поводу вопросов. да может быть асинхронным, дожидаемся результата через await и возвращаем новое значение из reduce, и добавил также обработку ошибок, если будут любые ошибки: в асинхронных функциях, промизах, которые они возвращает, в функции reducer, то промис будет отреджекчен

2018-08-04 14:38 UTC, thoughtspile commented
О нет! Промисы опять запускаются одновременно, а не ждут друг друга: проверьте на `() => console.log(2) || new Promise(ok => setTimeout(ok, 5000));`. 

Ошибки в самих промисах и в редьюсере проглатываются:
```js
promiseReduce([() => Promise.reject(10)], (a, x) => a + x, 0).catch(() => console.error('err'))
promiseReduce([() => 1], () => { throw new Error() }, 0).catch(() => console.error('err'))
```

Советую использовать голые промисы, без async / await — так проще понимать, что чего ждет. `new Promise` в данном случае можно заменить на `Promise.resolve / reject`

2018-08-04 16:43 UTC, Cornpop456 commented
Обработку ошибок поправил, а что касается того, чтобы промисы друг друга ждали, написал свой асинхронный reduce, так как так и не смог сделать со встроенным Array.prototype.reduce, так как он не дожидаясь исполнения промиса, продолжал работу и выполнял функции в массиве.

2018-08-05 06:59 UTC, thoughtspile commented
Обработка ошибок супер. Разбиение на 2 функции кажется мне неестественным — может всё же через reduce? Подскажу: главное — не запускать промисы _прямо_ в теле редьюсера. Возможно, алгоритм reduce-итерации словами поможет?

- ждём previous,
- вызываем current и ждем результат,
- вызываем reducer с результатами previous и current,
- новую цепочку передаем дальше.

2018-08-05 08:06 UTC, Cornpop456 commented
Да, разобрался все таки)

2018-08-05 10:25 UTC, thoughtspile requested changes
Ура, почти!

2018-08-05 10:25 UTC, thoughtspile commented on javascript/promiseReduce.js
> +        if (!accum.then) accum = Promise.resolve(accum);
Можно сразу сделать его промисом

2018-08-05 10:25 UTC, thoughtspile commented on javascript/promiseReduce.js
> +            .catch(err => { throw err });
что делает эта строка?

2018-08-05 10:31 UTC, Cornpop456 commented on javascript/promiseReduce.js
> +        if (!accum.then) accum = Promise.resolve(accum);
Изменил

2018-08-05 10:33 UTC, Cornpop456 commented on javascript/promiseReduce.js
> +            .catch(err => { throw err });
Ловит ошибку и пробрасывает ее дальше,  можно было делать Promise.reject(err), но throw автоматически оборачивается в отреджекченый промис, укороченный синтаксис)

2018-08-05 10:51 UTC, Cornpop456 commented on javascript/promiseReduce.js
> +            .catch(err => { throw err });
Хотя наверное она вообще не нужна, ошибка все равно будет поймана в catch после вызова promiseReduce(...).catch(...)

2018-08-05 18:27 UTC, merged